let flexColumns = document.querySelectorAll(`.flexColumn`);
const imageTable = [
    { prompt: `Film still cinematic photography, tilt angle, perfect composition, hyperdetailed forest, autumn theme, archaic military mech walking in a swamp, ripples of water move, biomechanical man and a mech, smoking heap of a spaceship collision in the background, natural aura, light blue aura, black aura, sunset`, negprompt: `easynegative, watermark, low quality, medium quality, blurry, censored, wrinkles, deformed, mutated text, watermark, low quality, medium quality, blurry, censored, wrinkles, deformed, mutated, embedding:easynegative`, src: `images/0.jpg` },
    { prompt: `Film still cinematic photography, tilt angle, perfect composition, hyperdetailed forest, autumn theme, archaic military mech walking in a swamp, ripples of water move, biomechanical man and a mech, smoking heap of a spaceship collision in the background, natural aura, light blue aura, black aura, sunset`, negprompt: `easynegative, watermark, low quality, medium quality, blurry, censored, wrinkles, deformed, mutated text, watermark, low quality, medium quality, blurry, censored, wrinkles, deformed, mutated, embedding:easynegative`, src: `images/1.jpg` },
    { prompt: `Film still cinematic photography, tilt angle, perfect composition, hyperdetailed forest, autumn theme, archaic military mech walking in a swamp, ripples of water move, biomechanical man and a mech, smoking heap of a spaceship collision in the background, natural aura, light blue aura, black aura, sunset`, negprompt: `easynegative, watermark, low quality, medium quality, blurry, censored, wrinkles, deformed, mutated text, watermark, low quality, medium quality, blurry, censored, wrinkles, deformed, mutated, embedding:easynegative`, src: `images/other-0.jpg` },
    { prompt: `Film still cinematic photography, tilt angle, perfect composition, hyperdetailed forest, autumn theme, archaic military mech walking in a swamp, ripples of water move, biomechanical man and a mech, smoking heap of a spaceship collision in the background, natural aura, light blue aura, black aura, sunset`, negprompt: `easynegative, watermark, low quality, medium quality, blurry, censored, wrinkles, deformed, mutated text, watermark, low quality, medium quality, blurry, censored, wrinkles, deformed, mutated, embedding:easynegative`, src: `images/2.jpg` },
    { prompt: `Film still cinematic photography, tilt angle, perfect composition, hyperdetailed forest, autumn theme, archaic military mech walking in a swamp, ripples of water move, biomechanical man and a mech, smoking heap of a spaceship collision in the background, natural aura, light blue aura, black aura, sunset`, negprompt: `easynegative, watermark, low quality, medium quality, blurry, censored, wrinkles, deformed, mutated text, watermark, low quality, medium quality, blurry, censored, wrinkles, deformed, mutated, embedding:easynegative`, src: `images/other-1.jpg` },
    { prompt: `Man, futuristic armor, full body, deep Space, space armor suit, armor, style armor blu and red lights, gray and light blue metal chromed armor, red and blue lights, metal armor, diffusion lights on armor, smooth helmet, grey metal chromed armor, aggressive looking, epic helmet, aggressive helmet, Eva helmet, galaxy, city closed street background`, negprompt: `Nude, deformation, asian space ship, repeating, red hair, red head, hallway, red armor, ironman, face, showing face, hair (showing hair: 2.0) tight suit, tits, boobs, red armor`, src: `images/3.jpg` },
    { prompt: `Man, futuristic armor, full body, deep Space, space armor suit, armor, style armor blu and red lights, gray and light blue metal chromed armor, red and blue lights, metal armor, diffusion lights on armor, smooth helmet, grey metal chromed armor, aggressive looking, epic helmet, aggressive helmet, Eva helmet, galaxy, city closed street background`, negprompt: `Nude, deformation, asian space ship, repeating, red hair, red head, hallway, red armor, ironman, face, showing face, hair (showing hair: 2.0) tight suit, tits, boobs, red armor`, src: `images/4.jpg` },
    { prompt: `Man, futuristic armor, full body, deep Space, space armor suit, armor, style armor blu and red lights, gray and light blue metal chromed armor, red and blue lights, metal armor, diffusion lights on armor, smooth helmet, grey metal chromed armor, aggressive looking, epic helmet, aggressive helmet, Eva helmet, galaxy, city closed street background`, negprompt: `Nude, deformation, asian space ship, repeating, red hair, red head, hallway, red armor, ironman, face, showing face, hair (showing hair: 2.0) tight suit, tits, boobs, red armor`, src: `images/5.jpg` },
    { prompt: `juicy burger, dark cinematic, Kodak RAW`, negprompt: `clothes`, src: `images/6.jpg` },
    { prompt: `circuitboard egyptian pyramid`, negprompt: ``, src: `images/7.jpg` },
    {
        prompt: `tilt-shift photography,<lora:citySDXL:1>,the photo shows urban scenery,
    tilt-shift photography of A fairy-tale town,extreme detail,unreal engine,octane render,natural light,halo effects,8k,wallpaper,
    photograph shot with Canon EOS 90D with Canon EF-S 18-135mm f-3.5-5.6 IS USM`,
        negprompt: `ugly, deformed, noisy, blurry, low contrast, camera, blurry`,
        src: `images/8.jpg`,
    },
    {
        prompt: `tilt-shift photography,<lora:citySDXL:1>,the photo shows urban scenery,
    tilt-shift photography of A fairy-tale town,extreme detail,unreal engine,octane render,natural light,halo effects,8k,wallpaper,
    photograph shot with Canon EOS 90D with Canon EF-S 18-135mm f-3.5-5.6 IS USM`,
        negprompt: `ugly, deformed, noisy, blurry, low contrast, camera, blurry`,
        src: `images/9.jpg`,
    },
    {
        prompt: `tilt-shift photography,<lora:citySDXL:1>,the photo shows urban scenery,
    tilt-shift photography of A fairy-tale town,extreme detail,unreal engine,octane render,natural light,halo effects,8k,wallpaper,
    photograph shot with Canon EOS 90D with Canon EF-S 18-135mm f-3.5-5.6 IS USM`,
        negprompt: `ugly, deformed, noisy, blurry, low contrast, camera, blurry`,
        src: `images/other-3.jpg`,
    },
    {
        prompt: `tilt-shift photography,<lora:citySDXL:1>,the photo shows urban scenery,
    tilt-shift photography of A fairy-tale town,extreme detail,unreal engine,octane render,natural light,halo effects,8k,wallpaper,
    photograph shot with Canon EOS 90D with Canon EF-S 18-135mm f-3.5-5.6 IS USM`,
        negprompt: `ugly, deformed, noisy, blurry, low contrast, camera, blurry`,
        src: `images/10.jpg`,
    },
    {
        prompt: `tilt-shift photography,<lora:citySDXL:1>,the photo shows urban scenery,
    tilt-shift photography of A fairy-tale town,extreme detail,unreal engine,octane render,natural light,halo effects,8k,wallpaper,
    photograph shot with Canon EOS 90D with Canon EF-S 18-135mm f-3.5-5.6 IS USM`,
        negprompt: `ugly, deformed, noisy, blurry, low contrast, camera, blurry`,
        src: `images/other-2.jpg`,
    },
    { prompt: `A female futuristic astronaut explorer in white and orange suit, wandering in a dense Pandora forest`, negprompt: ``, src: `images/11.jpg` },
    { prompt: `A female futuristic astronaut explorer in white and orange suit, wandering in a dense Pandora forest`, negprompt: ``, src: `images/12.jpg` },
    { prompt: `a cute small mouse with ginger fur. Adorable. Hufflepuff scarf, black and yellow stripes, Glasses. reading a book. chalk dust`, negprompt: ``, src: `images/13.jpg` },
    { prompt: `a cute small cat with ginger fur. Adorable. Hufflepuff scarf, black and yellow stripes, Glasses. reading a book. chalk dust`, negprompt: ``, src: `images/other-9.jpg` },
    { prompt: `landscape by Alena Aenami`, negprompt: ``, src: `images/14.jpg` },
    { prompt: `a bored student girl on her laptop, on a desk, cozy room, headphones, large window, vibrant colors, lineart, Studio Ghibli`, negprompt: ``, src: `images/15.jpg` },
    { prompt: `a bored student girl on her laptop, on a desk, cozy room, headphones, large window, vibrant colors, lineart, Studio Ghibli`, negprompt: ``, src: `images/16.jpg` },
    { prompt: `a bored student girl on her laptop, on a desk, cozy room, headphones, large window, vibrant colors, lineart, Studio Ghibli`, negprompt: ``, src: `images/17.jpg` },
    { prompt: `two students working on a laptop, cozy room, large window, vibrant colors, lineart`, negprompt: ``, src: `images/18.jpg` },
    { prompt: `huge sacred European castle on the mountains, surrounded by many small villages, castles and mountains with many (waterfalls of different sizes),(the castle is composed of white brick walls), with gold paint on them, very gorgeous and noble, very complicated decoration, vegetation, blue sky, clouds floating in the mountains,birds flying, very clear, film level lighting, 4k, masterpiece,high resolution,Variegated color filter`, negprompt: `((worst quality:1.2), (low quality:1.2), mutated hands and fingers, bad anatomy, wrong anatomy, ugly, mutation:1.2),(worst quality, low quality:1.4), lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry,lowres,watermark,Twisted and deformed bodies, twisted and deformed faces,badhandv4,ng_deepnegative_v1_75t, By bad artist -negNSFW`, src: `images/other-5.jpg` },
    { prompt: `huge sacred European castle on the mountains, surrounded by many small villages, castles and mountains with many (waterfalls of different sizes),(the castle is composed of white brick walls), with gold paint on them, very gorgeous and noble, very complicated decoration, vegetation, blue sky, clouds floating in the mountains,birds flying, very clear, film level lighting, 4k, masterpiece,high resolution,Variegated color filter`, negprompt: `((worst quality:1.2), (low quality:1.2), mutated hands and fingers, bad anatomy, wrong anatomy, ugly, mutation:1.2),(worst quality, low quality:1.4), lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry,lowres,watermark,Twisted and deformed bodies, twisted and deformed faces,badhandv4,ng_deepnegative_v1_75t, By bad artist -negNSFW`, src: `images/19.jpg` },
    { prompt: `huge sacred European castle on the mountains, surrounded by many small villages, castles and mountains with many (waterfalls of different sizes),(the castle is composed of white brick walls), with gold paint on them, very gorgeous and noble, very complicated decoration, vegetation, blue sky, clouds floating in the mountains,birds flying, very clear, film level lighting, 4k, masterpiece,high resolution,Variegated color filter`, negprompt: `((worst quality:1.2), (low quality:1.2), mutated hands and fingers, bad anatomy, wrong anatomy, ugly, mutation:1.2),(worst quality, low quality:1.4), lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry,lowres,watermark,Twisted and deformed bodies, twisted and deformed faces,badhandv4,ng_deepnegative_v1_75t, By bad artist -negNSFW`, src: `images/other-4.jpg` },
    { prompt: `huge sacred European castle on the mountains, surrounded by many small villages, castles and mountains with many (waterfalls of different sizes),(the castle is composed of white brick walls), very gorgeous and noble, very complicated decoration, vegetation, blue sky, clouds floating in the mountains,birds flying, very clear, film level lighting, 4k, masterpiece,high resolution,Variegated color filter`, negprompt: `((worst quality:1.2), (low quality:1.2), mutated hands and fingers, bad anatomy, wrong anatomy, ugly, mutation:1.2),(worst quality, low quality:1.4), lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry,lowres,watermark,Twisted and deformed bodies, twisted and deformed faces,badhandv4,ng_deepnegative_v1_75t, By bad artist -negNSFW`, src: `images/20.jpg` },

    { prompt: `huge sacred European castle on the mountains, surrounded by many small villages, castles and mountains with many (waterfalls of different sizes),(the castle is composed of white brick walls), very gorgeous and noble, very complicated decoration, vegetation, blue sky, clouds floating in the mountains,birds flying, very clear, film level lighting, 4k, masterpiece,high resolution,Variegated color filter`, negprompt: `(worst quality:1.2), (low quality:1.2), mutated hands and fingers, bad anatomy, wrong anatomy, ugly, mutation:1.2),(worst quality, low quality:1.4), lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry,lowres,watermark,Twisted and deformed bodies, twisted and deformed faces,badhandv4,ng_deepnegative_v1_75t, By bad artist -negNSFW`, src: `images/21.jpg` },
    { prompt: `professional close-up portrait photography of the face of a beautiful woman at baseball stadium during Twilight, Nikon Z9`, negprompt: ``, src: `images/22.jpg` },
    { prompt: `cinematic film still cinematic still no humans, glowing, space, fflix_dmatter . emotional, harmonious, vignette, highly detailed, high budget, bokeh, cinemascope, moody, epic, gorgeous, film grain, grainy", "no humans, glowing, space, fflix_dmatter, extremely detailed, drawn by ruan jia, ruan jia, greg rutkowski, cinematic, artstation, key art, hyperrealism, octane render, 8 k. shallow depth of field, vignette, highly detailed, high budget, bokeh, cinemascope, moody, epic, gorgeous, film grain, grainy`, negprompt: `anime, cartoon, graphic, text, painting, crayon, graphite, abstract, glitch, deformed, mutated, ugly, disfigured, anime, cartoon, graphic, text, painting, crayon, graphite, abstract, glitch, deformed, mutated, ugly, disfigured, verybadimagenegative_v1.3, ng_deepnegative_v1_75t, easynegative, (worst quality, low quality, illustration, 3d, 2d, painting, cartoons, sketch), bad anatomy, tooth, open mouth, bad hand, bad fingers, watermark, deformed, distorted, disfigured, poorly drawn,`, src: `images/23.jpg` },
    { prompt: `cinematic film still cinematic still no humans, glowing, space, fflix_dmatter . emotional, harmonious, vignette, highly detailed, high budget, bokeh, cinemascope, moody, epic, gorgeous, film grain, grainy", "no humans, glowing, space, fflix_dmatter, extremely detailed, drawn by ruan jia, ruan jia, greg rutkowski, cinematic, artstation, key art, hyperrealism, octane render, 8 k. shallow depth of field, vignette, highly detailed, high budget, bokeh, cinemascope, moody, epic, gorgeous, film grain, grainy`, negprompt: `anime, cartoon, graphic, text, painting, crayon, graphite, abstract, glitch, deformed, mutated, ugly, disfigured, anime, cartoon, graphic, text, painting, crayon, graphite, abstract, glitch, deformed, mutated, ugly, disfigured, verybadimagenegative_v1.3, ng_deepnegative_v1_75t, easynegative, (worst quality, low quality, illustration, 3d, 2d, painting, cartoons, sketch), bad anatomy, tooth, open mouth, bad hand, bad fingers, watermark, deformed, distorted, disfigured, poorly drawn,`, src: `images/24.jpg` },
    { prompt: `cinematic film still cinematic still no humans, glowing, space, fflix_dmatter . emotional, harmonious, vignette, highly detailed, high budget, bokeh, cinemascope, moody, epic, gorgeous, film grain, grainy", "no humans, glowing, space, fflix_dmatter, extremely detailed, drawn by ruan jia, ruan jia, greg rutkowski, cinematic, artstation, key art, hyperrealism, octane render, 8 k. shallow depth of field, vignette, highly detailed, high budget, bokeh, cinemascope, moody, epic, gorgeous, film grain, grainy`, negprompt: `anime, cartoon, graphic, text, painting, crayon, graphite, abstract, glitch, deformed, mutated, ugly, disfigured, anime, cartoon, graphic, text, painting, crayon, graphite, abstract, glitch, deformed, mutated, ugly, disfigured, verybadimagenegative_v1.3, ng_deepnegative_v1_75t, easynegative, (worst quality, low quality, illustration, 3d, 2d, painting, cartoons, sketch), bad anatomy, tooth, open mouth, bad hand, bad fingers, watermark, deformed, distorted, disfigured, poorly drawn,`, src: `images/25.jpg` },
    { prompt: `cinematic film still cinematic still no humans, glowing, space, fflix_dmatter . emotional, harmonious, vignette, highly detailed, high budget, bokeh, cinemascope, moody, epic, gorgeous, film grain, grainy", "no humans, glowing, space, fflix_dmatter, extremely detailed, drawn by ruan jia, ruan jia, greg rutkowski, cinematic, artstation, key art, hyperrealism, octane render, 8 k. shallow depth of field, vignette, highly detailed, high budget, bokeh, cinemascope, moody, epic, gorgeous, film grain, grainy`, negprompt: `anime, cartoon, graphic, text, painting, crayon, graphite, abstract, glitch, deformed, mutated, ugly, disfigured, anime, cartoon, graphic, text, painting, crayon, graphite, abstract, glitch, deformed, mutated, ugly, disfigured, verybadimagenegative_v1.3, ng_deepnegative_v1_75t, easynegative, (worst quality, low quality, illustration, 3d, 2d, painting, cartoons, sketch), bad anatomy, tooth, open mouth, bad hand, bad fingers, watermark, deformed, distorted, disfigured, poorly drawn,`, src: `images/other-10.jpg` },
    { prompt: `cinematic film still cinematic still no humans, glowing, space, fflix_dmatter . emotional, harmonious, vignette, highly detailed, high budget, bokeh, cinemascope, moody, epic, gorgeous, film grain, grainy", "no humans, glowing, space, fflix_dmatter, extremely detailed, drawn by ruan jia, ruan jia, greg rutkowski, cinematic, artstation, key art, hyperrealism, octane render, 8 k. shallow depth of field, vignette, highly detailed, high budget, bokeh, cinemascope, moody, epic, gorgeous, film grain, grainy`, negprompt: `anime, cartoon, graphic, text, painting, crayon, graphite, abstract, glitch, deformed, mutated, ugly, disfigured, anime, cartoon, graphic, text, painting, crayon, graphite, abstract, glitch, deformed, mutated, ugly, disfigured, verybadimagenegative_v1.3, ng_deepnegative_v1_75t, easynegative, (worst quality, low quality, illustration, 3d, 2d, painting, cartoons, sketch), bad anatomy, tooth, open mouth, bad hand, bad fingers, watermark, deformed, distorted, disfigured, poorly drawn,`, src: `images/26.jpg` },
    { prompt: `glowing, space, fflix_dmatter . emotional, harmonious, vignette, highly detailed, high budget, bokeh, cinemascope, moody, epic, gorgeous, film grain, grainy", "no humans, glowing, space, fflix_dmatter, extremely detailed, drawn by ruan jia, ruan jia, greg rutkowski, cinematic, artstation, key art, hyperrealism, octane render, 8 k. shallow depth of field, vignette, highly detailed, high budget, bokeh, cinemascope, moody, epic, gorgeous, film grain, grainy`, negprompt: ``, src: `images/27.jpg` },
    { prompt: `professional close-up portrait photography of the face of a beautiful woman at baseball stadium during Twilight, Nikon Z9`, negprompt: ``, src: `images/other-6.jpg` },
    { prompt: `professional close-up portrait photography of the face of a beautiful woman at baseball stadium during Twilight, Nikon Z9`, negprompt: ``, src: `images/28.jpg` },
    { prompt: `professional close-up portrait photography of the face of a beautiful woman at baseball stadium during Twilight, Nikon Z9`, negprompt: ``, src: `images/29.jpg` },
    { prompt: `professional close-up portrait photography of the face of a beautiful woman at baseball stadium during Twilight, Nikon Z9`, negprompt: ``, src: `images/30.jpg` },

    { prompt: `professional close-up portrait photography of the face of a beautiful woman at baseball stadium during Twilight, Nikon Z9`, negprompt: ``, src: `images/31.jpg` },
    { prompt: `professional close-up portrait photography of the face of a beautiful woman in the mountains, Nikon Z9 photography`, negprompt: ``, src: `images/32.jpg` },
    { prompt: `professional close-up portrait photography of the face of a beautiful woman in the mountains, winter scenery Nikon Z9 photography`, negprompt: ``, src: `images/33.jpg` },
    { prompt: `professional close-up portrait photography of the face and shoulders of a beautiful woman in the mountains, winter scenery Nikon Z9`, negprompt: ``, src: `images/34.jpg` },
    { prompt: `Pierre joubert, painting of a royal ship`, negprompt: ``, src: `images/35.jpg` },
    { prompt: `Pierre joubert, painting of a royal ship`, negprompt: ``, src: `images/36.jpg` },
    { prompt: `Painting of a royal ship`, negprompt: ``, src: `images/37.jpg` },
    { prompt: `tilt-shift photography,the photo shows urban scenery, tilt-shift photography of A fairy-tale town,extreme detail,unreal engine,octane render,natural light,halo effects,8k,wallpaper, mayamaze, caveruinsAerial photograph shot with Canon EOS 90D with Canon EF-S 18-135mm f-3.5-5.6 IS USM,`, negprompt: `ugly, deformed, noisy, blurry, low contrast, camera, blurry`, src: `images/38.jpg` },
    { prompt: `tilt-shift photography,the photo shows urban scenery, tilt-shift photography of A fairy-tale town,extreme detail,unreal engine,octane render,natural light,halo effects,8k,wallpaper, mayamaze, caveruinsAerial photograph shot with Canon EOS 90D with Canon EF-S 18-135mm f-3.5-5.6 IS USM,`, negprompt: `ugly, deformed, noisy, blurry, low contrast, camera, blurry`, src: `images/other-7.jpg` },
    { prompt: `photo of a city, the photo shows urban scenery, tilt-shift photography of town, extreme detail,octane render,natural light,halo effects,8k,wallpaper, mayamaze, caveruinsAerial photograph shot with Canon EOS 90D with Canon EF-S 18-135mm f-3.5-5.6 IS USM,`, negprompt: `ugly, deformed, noisy, blurry, low contrast, camera, blurry`, src: `images/39.jpg` },
    { prompt: `photo of a city, the photo shows urban scenery, tilt-shift photography of town, extreme detail,octane render,natural light,halo effects,8k,wallpaper, mayamaze, caveruinsAerial photograph shot with Canon EOS 90D with Canon EF-S 18-135mm f-3.5-5.6 IS USM,`, negprompt: `ugly, deformed, noisy, blurry, low contrast, camera, blurry`, src: `images/40.jpg` },

    { prompt: `photo of a city, the photo shows urban scenery, tilt-shift photography of town, extreme detail,octane render,natural light,halo effects,8k,wallpaper, mayamaze, caveruinsAerial photograph shot with Canon EOS 90D with Canon EF-S 18-135mm f-3.5-5.6 IS USM,`, negprompt: `ugly, deformed, noisy, blurry, low contrast, camera, blurry`, src: `images/41.jpg` },
    { prompt: `photo of a city, the photo shows urban scenery, tilt-shift photography of town, extreme detail,octane render,natural light,halo effects,8k,wallpaper, mayamaze, caveruinsAerial photograph shot with Canon EOS 90D with Canon EF-S 18-135mm f-3.5-5.6 IS USM,`, negprompt: `ugly, deformed, noisy, blurry, low contrast, camera, blurry`, src: `images/42.jpg` },
    { prompt: `a photo of a high detailed pirate ship with skulls, god rays, gothic, (dark fantasy:2), volumetric lighting, shadows, in flames, burned, bow looks like skull with open jaw with fire`, negprompt: `unrealistic, not detailed`, src: `images/43.jpg` },
    { prompt: `Design a (((Chinese demon))) that embodies the intersection of malevolence and mystique. Its features include intricate horns, ethereal scales, and eyes aflame with otherworldly wisdom. Uncover its origins within ancient Chinese folklore or its place in the celestial hierarchy. Explore its motivations, whether driven by revenge, power, or redemption. Invite writers to infuse this character with cultural nuances, making it a complex figure that resonates with the rich tapestry of Chinese mythology`, negprompt: `bad anatomy, poorly drawn face, out of frame, gibberish, lowres, lowres`, src: `images/44.jpg` },
    { prompt: `Design a (((Chinese demon))) that embodies the intersection of malevolence and mystique. Its features include intricate horns, ethereal scales, and eyes aflame with otherworldly wisdom. Uncover its origins within ancient Chinese folklore or its place in the celestial hierarchy. Explore its motivations, whether driven by revenge, power, or redemption. Invite writers to infuse this character with cultural nuances, making it a complex figure that resonates with the rich tapestry of Chinese mythology`, negprompt: `bad anatomy, poorly drawn face, out of frame, gibberish, lowres, lowres`, src: `images/45.jpg` },
    { prompt: `Design a (((japaneese cat))) that embodies the intersection of malevolence and mystique. Its features include intricate horns, ethereal scales, and eyes aflame with otherworldly wisdom. Uncover its origins within ancient Chinese folklore or its place in the celestial hierarchy. Explore its motivations, whether driven by revenge, power, or redemption. Invite writers to infuse this character with cultural nuances, making it a complex figure that resonates with the rich tapestry of Chinese mythology`, negprompt: `bad anatomy, poorly drawn face, out of frame, gibberish, lowres, lowres`, src: `images/46.jpg` },
    { prompt: `spiral galaxy inside a glass jar, the jar stands on the kitchen table, high resolution, high detail`, negprompt: ``, src: `images/47.jpg` },
    { prompt: `spiral galaxy inside a glass jar, the jar stands on the kitchen table, high resolution, high detail`, negprompt: ``, src: `images/48.jpg` },
    { prompt: `spiral galaxy inside a glass jar, the jar stands on the kitchen table, high resolution, high detail`, negprompt: ``, src: `images/other-16.jpg` },
    { prompt: `hand drawn sketch illustration of a beautiful dragon earthen dragon, flowers moss, tree branches, dryad, symmetrical dragon horns, illustration, watercolor sketch, (best quality)), intricate detailed,`, negprompt: `double ears,tattoos, plastic, octane render, text, writing, ugly, deformed, simultaneous, bad lighting, blurry, text, watermark, plastic, 3d, cartoon, monochromatic, low quality`, src: `images/49.jpg` },
    { prompt: `(dark magic), (grim),focus on a cat, dynamic pose,(intricate details), (hyperdetailed), 8k hdr, high detailed, lot of details, high quality, soft cinematic light, dramatic atmosphere, atmospheric perspective`, negprompt: ``, src: `images/50.jpg` },

    { prompt: `(dark magic), (grim),focus on a cat, dynamic pose,(intricate details), (hyperdetailed), 8k hdr, high detailed, lot of details, high quality, soft cinematic light, dramatic atmosphere, atmospheric perspective`, negprompt: ``, src: `images/51.jpg` },
    { prompt: `focus on a cat, dynamic pose,(intricate details), (hyperdetailed), 8k hdr, high detailed, lot of details, high quality, soft cinematic light, atmospheric perspective`, negprompt: ``, src: `images/52.jpg` },
    { prompt: `focus on a cat, dynamic pose,(intricate details), (hyperdetailed), 8k hdr, high detailed, lot of details, high quality, soft cinematic light, atmospheric perspective`, negprompt: ``, src: `images/53.jpg` },
    { prompt: `focus on a cat, dynamic pose,(intricate details), (hyperdetailed), 8k hdr, high detailed, lot of details, high quality, soft cinematic light, atmospheric perspective`, negprompt: ``, src: `images/54.jpg` },
    { prompt: `focus on a dog, dynamic pose,(intricate details), (hyperdetailed), 8k hdr, high detailed, lot of details, high quality, soft cinematic light, atmospheric perspective`, negprompt: ``, src: `images/55.jpg` },
    { prompt: `focus on a dog, husky, dynamic pose,(intricate details), (hyperdetailed), 8k hdr, high detailed, lot of details, high quality, soft cinematic light, atmospheric perspective`, negprompt: ``, src: `images/other-8.jpg` },
    { prompt: `focus on a dog, german shepard, dynamic pose,(intricate details), (hyperdetailed), 8k hdr, high detailed, lot of details, high quality, soft cinematic light, atmospheric perspective`, negprompt: ``, src: `images/56.jpg` },
    { prompt: `Full bosy samurai character, Celestial, spiral, (volcanic brilliance), (a revolutionary union of Renaissance Pyrography, Lava Leviathan), wood grains of history, molten horse:3.0 alchemist:0.3, obsidian protector:0.9, burnt forest tapestries, flame-touched:2.2, charred semblance, igneous etch marks, (rust and magma reds:1.7), fiery shades, ember-enchanter, alt_burn, liquid gold glow, ultraviolet lens technique, wood char emphasis, cyanotype process, acrylic fusion, bokeh spread lens, 20k inferno, zenith's fierce glow, ember-illuminated, cavernous contrast, heat haze allure. Sculpted in the atmospheric realms of Ian McQue and finessed by Jama Jurabaev, this artwork radiates warmth and history, commanding profound introspection. `, negprompt: `tiling,  poorly drawn hands,  poorly drawn feet,  poorly drawn face,  out of frame,  extra limbs,  body out of frame,  blurry,  bad anatomy,  blurred,  watermark,  grainy,  signature,  cut off,  draft,   text,  logo`, src: `images/57.jpg` },
    { prompt: `Full bosy samurai character, Celestial, spiral, (volcanic brilliance), (a revolutionary union of Renaissance Pyrography, Lava Leviathan), wood grains of history, molten horse:3.0 alchemist:0.3, obsidian protector:0.9, burnt forest tapestries, flame-touched:2.2, charred semblance, igneous etch marks, (rust and magma reds:1.7), fiery shades, ember-enchanter, alt_burn, liquid gold glow, ultraviolet lens technique, wood char emphasis, cyanotype process, acrylic fusion, bokeh spread lens, 20k inferno, zenith's fierce glow, ember-illuminated, cavernous contrast, heat haze allure. Sculpted in the atmospheric realms of Ian McQue and finessed by Jama Jurabaev, this artwork radiates warmth and history, commanding profound introspection. `, negprompt: `tiling,  poorly drawn hands,  poorly drawn feet,  poorly drawn face,  out of frame,  extra limbs,  body out of frame,  blurry,  bad anatomy,  blurred,  watermark,  grainy,  signature,  cut off,  draft,   text,  logo`, src: `images/58.jpg` },
    { prompt: `a sumurai in a red armor`, negprompt: `tiling,  poorly drawn hands,  poorly drawn feet,  poorly drawn face,  out of frame,  extra limbs,  body out of frame,  blurry,  bad anatomy,  blurred,  watermark,  grainy,  signature,  cut off,  draft,   text,  logo`, src: `images/59.jpg` },
    { prompt: `pikachu themed birthday cake, yellow and brown colors, game icon, professional, high quality, super cute, kawaii, 8k, adorable`, negprompt: `low quality, blurry, deformed distorted`, src: `images/60.jpg` },

    { prompt: `a birthday cake pikachu themed, yellow and brown colors, professional, high quality, super cute, kawaii, 8k, adorable, on a table`, negprompt: `low quality, blurry, deformed distorted`, src: `images/61.jpg` },
    { prompt: `Cute dog wearing large sunglasses, looking to camera, in a circle, colorful, ink drops, ink circles, coffee stains, digital art, 8k, kawaii`, negprompt: ``, src: `images/62.jpg` },
    { prompt: `Cute dog wearing large sunglasses, looking to camera, in a circle, colorful, ink drops, ink circles, coffee stains, digital art, 8k, kawaii`, negprompt: ``, src: `images/63.jpg` },
    { prompt: `Cute husky dog wearing large sunglasses, looking to camera, in a circle, colorful, ink drops, ink circles, coffee stains, digital art, 8k, kawaii`, negprompt: ``, src: `images/64.jpg` },
    { prompt: `Cute corgi dog wearing large sunglasses, looking to camera, in a circle, colorful, ink drops, ink circles, coffee stains, digital art, 8k, kawaii`, negprompt: ``, src: `images/65.jpg` },
    { prompt: `Close up, a transparent shell of a glowing octopus in the depths of a glowing alien ocean, 8K ultra high definition, the winner of the competition,`, negprompt: ``, src: `images/66.jpg` },
    { prompt: `Close up, a transparent shell of a glowing octopus in the depths of a glowing alien ocean, 8K ultra high definition, the winner of the competition,`, negprompt: ``, src: `images/67.jpg` },
    { prompt: `Elon Musk as a Jedi, holding a purple lightsaber ((beautiful hands, beautiful eyes, beautiful skin, perfect anatomy, good lighting, good grip of the lightsaber, detailed))`, negprompt: `3d, cartoon, ugly face, deformed, missing digits, extra digits, bad eyes, Watermark, Text, censored, deformed, bad anatomy, disfigured, poorly drawn face, mutated, extra limb, ugly, poorly drawn hands, missing limb, floating limbs, disconnected limbs, disconnected head, malformed hands, long neck, mutated hands and fingers, bad hands, missing fingers, cropped, worst quality, low quality, mutation, poorly drawn, huge calf, bad hands, fused hand, missing hand, disappearing arms, disappearing thigh, disappearing calf, disappearing legs, missing fingers, fused fingers, abnormal eye proportion, Abnormal hands, abnormal legs, abnormal feet,  abnormal fingers, lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry`, src: `images/68.jpg` },
    { prompt: `silhouette style Triumphant against the elements, the athlete conquers the precipitous cliffside of Taroko Gorge, Taiwan. Majestic mountains pierce the heavens, while the swirling mist and fog envelop the rugged terrain, lending an air of mystery and intrigue. The woman, agile and assured, tackles the arduous climb with unwavering determination. A sense of drama permeates the scene, as she disappears briefly into the dense cloud cover, only to emerge stronger and more resolute. This award-winning landscape photograph embodies the spirit of adventure, inviting the viewer to explore the remote beauty of this natural wonder. . high contrast, minimalistic, black and white, stark, dramatic`, negprompt: `ugly, deformed, noisy, blurry, low contrast, color, realism, photorealistic, long neck, asymmetrical eyes, signature, watermark,`, src: `images/69.jpg` },
    { prompt: `one men on a path surrounded by a desert, the path is leading to a city `, negprompt: `ugly, deformed, noisy, blurry, low contrast, color, realism, photorealistic,  long neck, asymmetrical eyes, signature, watermark,`, src: `images/70.jpg` },

    { prompt: `one men on a path surrounded by a desert, the path is leading to a city `, negprompt: `ugly, deformed, noisy, blurry, low contrast, color, realism, photorealistic,  long neck, asymmetrical eyes, signature, watermark,`, src: `images/71.jpg` },
    { prompt: `one men on a path surrounded by a desert, the path is leading to a city, diuna movie style`, negprompt: `ugly, deformed, noisy, blurry, low contrast, color, realism, photorealistic,  long neck, asymmetrical eyes, signature, watermark,`, src: `images/72.jpg` },
    { prompt: `one men on a path surrounded by a desert, the path is leading to a city, diuna movie style`, negprompt: `ugly, deformed, noisy, blurry, low contrast, color, realism, photorealistic,  long neck, asymmetrical eyes, signature, watermark,`, src: `images/73.jpg` },
    { prompt: `a city on mars from the distance, the city is surrounded by a dome`, negprompt: `ugly, deformed, noisy, blurry, low contrast, color, realism, photorealistic,  long neck, asymmetrical eyes, signature, watermark,`, src: `images/74.jpg` },
    { prompt: `a view from the inside of a martian city, 8k hdr`, negprompt: `ugly, deformed, noisy, blurry, low contrast, color, realism, photorealistic,  long neck, asymmetrical eyes, signature, watermark,`, src: `images/75.jpg` },
    { prompt: `a view from the inside of a martian city, 8k hdr`, negprompt: `ugly, deformed, noisy, blurry, low contrast, color, realism, photorealistic, long neck, asymmetrical eyes, signature, watermark,`, src: `images/other-11.jpg` },
    { prompt: `ginger hair, blue eyes, cute little girl, 1girl, full body, puffy heart on dress, pink Colorful dress with white cat ears, rustic background, standing`, negprompt: `(worst quality, low quality:1.4), text, title, logo, signature`, src: `images/76.jpg` },
    { prompt: `ginger hair, blue eyes, cute little girl, 1girl, full body, puffy heart on dress, pink Colorful dress with white cat ears, rustic background, standing, anime lines`, negprompt: `(worst quality, low quality:1.4), text, title, logo, signature`, src: `images/77.jpg` },
    { prompt: `ginger hair, blue eyes, cute little girl, 1girl, full body, puffy heart on dress, pink Colorful dress with white cat ears, rustic background, standing, anime lines`, negprompt: `(worst quality, low quality:1.4), text, title, logo, signature`, src: `images/78.jpg` },
    { prompt: `Photo of artistic stone cup with 3D carvings, little mause theme with forest background, decorated with amber accents, masterpiece of art, visually stunning, intricate details, sharp focus, 55mm f/ 1.8 lens, depth of field, natural daylight`, negprompt: `blurry, painting, drawing, sketch, cartoon, anime, manga, render, CG, 3d, watermark, signature, label, (worst quality, low quality, normal quality:2),`, src: `images/79.jpg` },
    { prompt: `Photo of artistic stone vase with 3D carvings, little mause theme with forest background, decorated with amber accents, masterpiece of art, visually stunning, intricate details, sharp focus, 55mm f/ 1.8 lens, depth of field, natural daylight`, negprompt: `blurry, painting, drawing, sketch, cartoon, anime, manga, render, CG, 3d, watermark, signature, label, (worst quality, low quality, normal quality:2),`, src: `images/80.jpg` },

    { prompt: `by Guy Davis and Syd Mead, calmness, serenity,  wide angle,  hyper detailed, anime poster art, bold lines, award winning,  trending on ArtStation , (intricate details, masterpiece, best quality:1.4), looking at viewer, dynamic pose in the style of nicola samori `, negprompt: `(worst quality, greyscale),  watermark, username, signature, text, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, jpeg artifacts, bad feet, extra fingers, mutated hands, poorly drawn hands, bad proportions, extra limbs, disfigured, bad anatomy, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, mutated hands, fused fingers, too many fingers, long neck`, src: `images/81.jpg` },
    { prompt: `by Guy Davis and Syd Mead, calmness, serenity, wide angle, hyper detailed, anime poster art, bold lines, award winning, trending on ArtStation , (intricate details, masterpiece, best quality:1.4), looking at viewer, dynamic pose in the style of nicola samori`, negprompt: `(worst quality, greyscale), watermark, username, signature, text, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, jpeg artifacts, bad feet, extra fingers, mutated hands, poorly drawn hands, bad proportions, extra limbs, disfigured, bad anatomy, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, mutated hands, fused fingers, too many fingers, long neck`, src: `images/other-13.jpg` },
    { prompt: `by Guy Davis and Syd Mead, calmness, serenity,  wide angle,  hyper detailed, anime poster art, bold lines, award winning,  trending on ArtStation , (intricate details, masterpiece, best quality:1.4), looking at viewer, dynamic pose in the style of nicola samori `, negprompt: `(worst quality, greyscale),  watermark, username, signature, text, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, jpeg artifacts, bad feet, extra fingers, mutated hands, poorly drawn hands, bad proportions, extra limbs, disfigured, bad anatomy, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, mutated hands, fused fingers, too many fingers, long neck`, src: `images/82.jpg` },
    { prompt: `by Guy Davis and Syd Mead, calmness, serenity,  wide angle,  hyper detailed, anime poster art, bold lines, award winning,  trending on ArtStation , (intricate details, masterpiece, best quality:1.4), looking at viewer, dynamic pose in the style of nicola samori `, negprompt: `(worst quality, greyscale),  watermark, username, signature, text, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, jpeg artifacts, bad feet, extra fingers, mutated hands, poorly drawn hands, bad proportions, extra limbs, disfigured, bad anatomy, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, mutated hands, fused fingers, too many fingers, long neck`, src: `images/83.jpg` },
    { prompt: `by Guy Davis and Syd Mead, calmness, serenity,  wide angle,  hyper detailed, anime poster art, bold lines, award winning,  trending on ArtStation , (intricate details, masterpiece, best quality:1.4), looking at viewer, dynamic pose in the style of nicola samori `, negprompt: `(worst quality, greyscale),  watermark, username, signature, text, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, jpeg artifacts, bad feet, extra fingers, mutated hands, poorly drawn hands, bad proportions, extra limbs, disfigured, bad anatomy, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, mutated hands, fused fingers, too many fingers, long neck`, src: `images/84.jpg` },
    { prompt: `by Guy Davis and Syd Mead, calmness, serenity,  wide angle,  hyper detailed, anime poster art, bold lines, award winning,  trending on ArtStation , (intricate details, masterpiece, best quality:1.4), looking at viewer, dynamic pose in the style of nicola samori `, negprompt: `(worst quality, greyscale),  watermark, username, signature, text, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, jpeg artifacts, bad feet, extra fingers, mutated hands, poorly drawn hands, bad proportions, extra limbs, disfigured, bad anatomy, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, mutated hands, fused fingers, too many fingers, long neck`, src: `images/85.jpg` },
    { prompt: `by Guy Davis and Syd Mead, calmness, serenity,  wide angle,  hyper detailed, anime poster art, bold lines, award winning,  trending on ArtStation , (intricate details, masterpiece, best quality:1.4), looking at viewer, dynamic pose in the style of nicola samori `, negprompt: `(worst quality, greyscale),  watermark, username, signature, text, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, jpeg artifacts, bad feet, extra fingers, mutated hands, poorly drawn hands, bad proportions, extra limbs, disfigured, bad anatomy, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, mutated hands, fused fingers, too many fingers, long neck`, src: `images/86.jpg` },
    { prompt: `by Guy Davis and Syd Mead, calmness, serenity,  wide angle,  hyper detailed, anime poster art, bold lines, award winning,  trending on ArtStation , (intricate details, masterpiece, best quality:1.4), looking at viewer, dynamic pose in the style of nicola samori `, negprompt: `(worst quality, greyscale),  watermark, username, signature, text, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, jpeg artifacts, bad feet, extra fingers, mutated hands, poorly drawn hands, bad proportions, extra limbs, disfigured, bad anatomy, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, mutated hands, fused fingers, too many fingers, long neck`, src: `images/87.jpg` },
    { prompt: `by Guy Davis and Syd Mead, calmness, serenity,  wide angle,  hyper detailed, anime poster art, bold lines, award winning,  trending on ArtStation , (intricate details, masterpiece, best quality:1.4), looking at viewer, dynamic pose in the style of nicola samori `, negprompt: `(worst quality, greyscale),  watermark, username, signature, text, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, jpeg artifacts, bad feet, extra fingers, mutated hands, poorly drawn hands, bad proportions, extra limbs, disfigured, bad anatomy, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, mutated hands, fused fingers, too many fingers, long neck`, src: `images/88.jpg` },
    { prompt: `by Guy Davis and Syd Mead, calmness, serenity,  wide angle,  hyper detailed, anime poster art, bold lines, award winning,  trending on ArtStation , (intricate details, masterpiece, best quality:1.4), looking at viewer, dynamic pose in the style of nicola samori `, negprompt: `(worst quality, greyscale),  watermark, username, signature, text, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, jpeg artifacts, bad feet, extra fingers, mutated hands, poorly drawn hands, bad proportions, extra limbs, disfigured, bad anatomy, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, mutated hands, fused fingers, too many fingers, long neck`, src: `images/89.jpg` },
    { prompt: `by Guy Davis and Syd Mead, calmness, serenity,  wide angle,  hyper detailed, anime poster art, bold lines, award winning,  trending on ArtStation , (intricate details, masterpiece, best quality:1.4), looking at viewer, dynamic pose in the style of nicola samori `, negprompt: `(worst quality, greyscale),  watermark, username, signature, text, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, jpeg artifacts, bad feet, extra fingers, mutated hands, poorly drawn hands, bad proportions, extra limbs, disfigured, bad anatomy, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, mutated hands, fused fingers, too many fingers, long neck`, src: `images/90.jpg` },
    { prompt: `by Guy Davis and Syd Mead, calmness, serenity, wide angle, hyper detailed, anime poster art, bold lines, award winning, trending on ArtStation , (intricate details, masterpiece, best quality:1.4), looking at viewer, dynamic pose in the style of nicola samori`, negprompt: `(worst quality, greyscale), watermark, username, signature, text, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, jpeg artifacts, bad feet, extra fingers, mutated hands, poorly drawn hands, bad proportions, extra limbs, disfigured, bad anatomy, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, mutated hands, fused fingers, too many fingers, long neck`, src: `images/other-12.jpg` },

    { prompt: `score_9, score_8_up, 1girl, queen, bent over towards viewer, throne room, royal red dress, white gloves, legs crossed, solo, long hair, blonde hair, mid parted hair, heart, curvy, high heels, golden tiara, solo, hand to mouth`, negprompt: `score_6, score_5, score_4, pubic hair, pony, gaping, muscular, makeup, censored, furry, child, kid, chibi, teen`, src: `images/91.jpg` },
    { prompt: `score_9, score_8_up, 1girl, queen, bent over towards viewer, throne room, royal red dress, white gloves, legs crossed, solo, long hair, blonde hair, mid parted hair, heart, curvy, high heels, golden tiara, solo, hand to mouth `, negprompt: `score_6, score_5, score_4, pubic hair, pony, gaping, muscular, makeup, censored, furry, child, kid, chibi, teen`, src: `images/92.jpg` },
    { prompt: `Tiny cute ninja toy, standing character, soft smooth lighting, soft pastel colors, skottie young, 3d blender render, polycount, modular constructivism, pop surrealism, physically based rendering, square image`, negprompt: `worst quality, low quality, normal quality, lowres, low details`, src: `images/93.jpg` },
    { prompt: ` Tiny cute ninja toy, standing character, soft smooth lighting, soft pastel colors, skottie young, 3d blender render, polycount, modular constructivism, pop surrealism, physically based rendering, square image`, negprompt: `worst quality, low quality, normal quality, lowres, low details`, src: `images/94.jpg` },
    { prompt: `Tiny cute anime toy, standing character, soft smooth lighting, soft pastel colors, skottie young, 3d blender render, polycount, modular constructivism, pop surrealism, physically based rendering, square image`, negprompt: `worst quality, low quality, normal quality, lowres, low details`, src: `images/95.jpg` },
    { prompt: `Tiny cute anime toy, standing character, soft smooth lighting, soft pastel colors, skottie young, 3d blender render, polycount, modular constructivism, pop surrealism, physically based rendering, square image`, negprompt: `worst quality, low quality, normal quality, lowres, low details`, src: `images/other-14.jpg` },
    { prompt: `Tiny cute anime toy, standing character, soft smooth lighting, soft pastel colors, skottie young, 3d blender render, polycount, modular constructivism, pop surrealism, physically based rendering, square image`, negprompt: `worst quality, low quality, normal quality, lowres, low details`, src: `images/other-15.jpg` },
    { prompt: `Tiny cute anime toy, standing character, soft smooth lighting, soft pastel colors, skottie young, 3d blender render, polycount, modular constructivism, pop surrealism, physically based rendering, square image`, negprompt: `worst quality, low quality, normal quality, lowres, low details`, src: `images/96.jpg` },
    { prompt: `masterpiece, best quality, highres, aahuang, long hair, twintails, hair ribbon, small breasts, school uniform, white dress, detached sleeves, standing, cowboy shot, outdoors, smile, open mouth, leaning forward, arms behind back, cherry blossoms, looking at viewer`, negprompt: `EasyNegative, lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, (worst quality:1.2), low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, lowres graffiti, (low quality lowres simple background:1.1), (holding:1.5),`, src: `images/97.jpg` },
    { prompt: `by Eugene Galien-Laloue and Bruce Pennington,  (arctic , unusual , masterful:1.4), poster art, bold lines, hyper detailed, expressive,  award winning,  (landscape:1.4), (intricate details, masterpiece, best quality:1.4), studio lighting , looking at viewer, dynamic pose, wide angle view,`, negprompt: `(worst quality, greyscale),  watermark, username, signature, text, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, jpeg artifacts, bad feet, extra fingers, mutated hands, poorly drawn hands, bad proportions, extra limbs, disfigured, bad anatomy, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, mutated hands, fused fingers, too many fingers, long neck`, src: `images/98.jpg` },
    { prompt: `by Eugene Galien-Laloue and Bruce Pennington,  (arctic , unusual , masterful:1.4), poster art, bold lines, hyper detailed, expressive,  award winning,  (landscape:1.4), (intricate details, masterpiece, best quality:1.4), studio lighting , looking at viewer, dynamic pose, wide angle view,`, negprompt: `(worst quality, greyscale),  watermark, username, signature, text, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, jpeg artifacts, bad feet, extra fingers, mutated hands, poorly drawn hands, bad proportions, extra limbs, disfigured, bad anatomy, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, mutated hands, fused fingers, too many fingers, long neck`, src: `images/99.jpg` },
    { prompt: `by Eugene Galien-Laloue and Bruce Pennington,  (arctic , unusual , masterful:1.4), poster art, bold lines, hyper detailed, expressive,  award winning,  (landscape:1.4), (intricate details, masterpiece, best quality:1.4), studio lighting , looking at viewer, dynamic pose, wide angle view,`, negprompt: `(worst quality, greyscale),  watermark, username, signature, text, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, jpeg artifacts, bad feet, extra fingers, mutated hands, poorly drawn hands, bad proportions, extra limbs, disfigured, bad anatomy, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, mutated hands, fused fingers, too many fingers, long neck`, src: `images/100.jpg` },
    { prompt: `amazing quality, masterpiece, best quality, hyper detailed, ultra detailed, UHD, HDR, DOF, depth of field, wide-angle lens, detail eyes, Minions, solo, full body, hand up, (fighting stance:1.2), cute, kawaii, dynamic and vivid colors, fascinating, gorgeous sky, shiny dust, wind blows, extremely detailed,`, negprompt: `FastNegativeV2, watermark, signature, worst quality, low quality, normal quality, lowres, simple background, inaccurate limb, extra fingers, fewer fingers, missing fingers, extra arms, (extra legs:1.3), inaccurate eyes, bad composition, bad anatomy, error, extra digit, fewer digits, cropped, low res, worst quality, low quality, normal quality, jpeg artifacts, extra digit, fewer digits, trademark, watermark, artist's name, username, signature, text, words,`, src: `images/other-17.jpg` },
    { prompt: `amazing quality, masterpiece, best quality, hyper detailed, ultra detailed, UHD, HDR, DOF, depth of field, wide-angle lens, detail eyes, Minions, solo,  full body, holding sword, glowing sword, wearing ornate (yellow hybrid blue) armor, hand up, (fighting stance:1.2), cute, kawaii, (castle | temple | forest | mountain top | city | village | wilderness | snow land), dynamic and vivid colors, fascinating, gorgeous sky, shiny dust, wind blows,  extremely detailed,`, negprompt: `FastNegativeV2, watermark, signature, worst quality, low quality, normal quality, lowres, simple background, inaccurate limb, extra fingers, fewer fingers, missing fingers, extra arms, (extra legs:1.3), inaccurate eyes, bad composition, bad anatomy, error, extra digit, fewer digits, cropped, low res, worst quality, low quality, normal quality, jpeg artifacts, extra digit, fewer digits, trademark, watermark, artist's name, username, signature, text, words,`, src: `images/101.jpg` },
    { prompt: `amazing quality, masterpiece, best quality, hyper detailed, ultra detailed, UHD, HDR, DOF, depth of field, wide-angle lens, detail eyes, Minions, solo,  full body, hand up, (fighting stance:1.2), cute, kawaii, dynamic and vivid colors, fascinating, gorgeous sky, shiny dust, wind blows,  extremely detailed,`, negprompt: `FastNegativeV2, watermark, signature, worst quality, low quality, normal quality, lowres, simple background, inaccurate limb, extra fingers, fewer fingers, missing fingers, extra arms, (extra legs:1.3), inaccurate eyes, bad composition, bad anatomy, error, extra digit, fewer digits, cropped, low res, worst quality, low quality, normal quality, jpeg artifacts, extra digit, fewer digits, trademark, watermark, artist's name, username, signature, text, words,`, src: `images/102.jpg` },
    { prompt: `candid view, car chase, epic, action, cinematic, motion trails, colored inked, comics, graphic novel illustration, flat colors, highly detailed, large gradient, paper texture, go pro, color graded illustration, comics page`, negprompt: `boring, static, photography, bad perspective`, src: `images/103.jpg` },
    { prompt: `candid view, car chase, epic, action, cinematic, motion trails, colored inked, comics, graphic novel illustration, flat colors, highly detailed, large gradient, paper texture, go pro, color graded illustration, comics page`, negprompt: `boring, static, photography, bad perspective`, src: `images/104.jpg` },
    { prompt: `female, red under eye, under eye makeup, white eyes, white eyes, white eyelashes, blue hair, blue hair, flowing hair, flowing hair, glowing hair, glowing hair, while sharks, whale sharks, underwater, underwater, stoic face, calm face, beautiful, pretty, white dress, white dress, flowing dress, stars, stars in hair, pretty, shaded, glowing, glowing beautiful shading, glowing, under water, floating, floating`, negprompt: `bad quality, bad anatomy, worst quality, low quality, low resolution, extra fingers, blur, blurry, ugly, wrong proportions, watermark, image artifacts, lowres, jpeg artifacts, deformed, noisy image, deformation, corrupt image`, src: `images/105.jpg` },
    { prompt: `((pixelart)), a picture of an old car, night city on the background, (8k, RAW photo, best quality, masterpiece:1.2), trending on artstation, videogame art, `, negprompt: ``, src: `images/106.jpg` },
    { prompt: `((pixelart)), a picture of an old car, night city on the background, (8k, RAW photo, best quality, masterpiece:1.2), trending on artstation, videogame art, `, negprompt: ``, src: `images/107.jpg` },
    { prompt: `pixelart, 64 bit, a kitten pouncing, backyard in the background`, negprompt: ``, src: `images/108.jpg` },
    { prompt: `highly detailed isometric pixelart close-up transformer bumblebee robot,  white background, eboy style`, negprompt: ``, src: `images/109.jpg` },
    { prompt: `highly detailed isometric pixelart close-up of a harbor, eboy style`, negprompt: ``, src: `images/110.jpg` },

    { prompt: `highly detailed isometric pixelart close-up of a city located next to a beach, eboy style`, negprompt: ``, src: `images/111.jpg` },
    { prompt: `Double Exposure Style,Volumetric Lighting, a girl side view portrait, light depth, dramatic atmospheric lighting,Volumetric Lighting, double image ghost effect, image combination, double exposure style, background lightly brushed with the image of a futuristic city buildings`, negprompt: `blurry, worst quality`, src: `images/112.jpg` },
    { prompt: `(analog photo) of a chimp wearing a black suit with a white shirt and black necktie and wearing black Rayban style sunglasses , full body,, masterpiece, Fine art photography, award winning photography`, negprompt: `bowtie, human, illustration, drawing, painting, sketch, 3D, render, manga, child, childlike  grey scale`, src: `images/113.jpg` },
    { prompt: `film noir style, retro, chiaroscuro, photo of  a (complex architectural science fiction structure:1.4) by Apollonia Saintclair and Nicolas Delort and Alex Garant,  (illuminated , golden , masterful:1.4), bold lines, hyper detailed, award winning,  UHD, monochrome color palette, greyscale, high contrast, depth of field, black and white hue, (intricate details, masterpiece, best quality:1.4), extremely dramatic lighting with deep shadows, looking at viewer, dynamic pose, wide angle view,`, negprompt: `(worst quality, greyscale),  watermark, username, signature, text, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, jpeg artifacts, bad feet, extra fingers, mutated hands, poorly drawn hands, bad proportions, extra limbs, disfigured, bad anatomy, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, mutated hands, fused fingers, too many fingers, long neck, grey scale`, src: `images/114.jpg` },
    { prompt: `midnight, night street in town, deserted lane, fantasy, mystic, Realistic, Twilight, Dusky, Shadowy, Mysterious, 16K, 32K, UHD, absurdres, ultra-high resolution, 15K, 3D, Photographic Realism, Land Art, Romantic Landscape, atmospheric, Halcyo, Dreamy, Serene, Tranquil, Quaint Comfy, Hygge, Homely, Euphoric, Enchanting, Romantic, Arcane, Sorcerous, Miraculous, Bewitching, Mesmerizing, Dramatic lighting, Streetwise, Vintage, Antique, Haunting, Spiritual, Transcendent, Decima engine, Perfectly Focused, Complete Sharpness, Depth of Field, Evenly Focused, Full Depth, Sharp Focus, Phenomenal Masterwork, Work of Art, intricate details, vibrant, Opalescent colors, Breathtaking, Virtuoso, Carefully Designed, Artistic, Masterful, Perfectly Crafted, Refined, Screen Space Ambient Occlusion, Anisotropic Filtering, Depth Peeling, Environment Lighting, Atmospheric Scattering, Distortion, Global Illumination, Volumetric Lighting, Bloom, HDR, Compositing, Virtual Texturing, Post-Processing Effects, Procedural Generation, Procedural Texturing, Parallax Mapping, NPR Hatching, Physically-Based Rendering, Dynamic Weather Systems, Real-Time Reflections`, negprompt: `embedding:AC_Neg1, embedding:ImgFixerPre0.3, embedding:unaestheticXL_Alb2, (Asian:1.2), Chinese, (anime:1.2), second moon, extra moon, cartoon, illustration, (worst quality:1.5), (low quality:1.5), (normal quality:1.5),`, src: `images/115.jpg` },
    { prompt: `inspired by michael bay and syd mead, retrofuturism, a cinematic film still of a futuristic megacity, towering skyscrapers, sunset, (ornate bridges:1.1), dynamic composition, blade runner 2049 aesthetics, gradient sky, high quality photography, schneider super cinelux, sharp focus, award winning photo, 80mm, f2.8, ultra detailed, ultra high resolution, hdr, 8k, uhd`, negprompt: `ng-unaesthetic-xl_alb2, ng-zip2d-xl`, src: `images/116.jpg` },
    { prompt: `inspired by michael bay and syd mead, retrofuturism, a cinematic film still of a futuristic megacity, towering skyscrapers, sunset, (ornate bridges:1.1), dynamic composition, blade runner 2049 aesthetics, gradient sky, high quality photography, schneider super cinelux, sharp focus, award winning photo, 80mm, f2.8, ultra detailed, ultra high resolution, hdr, 8k, uhd`, negprompt: `ng-unaesthetic-xl_alb2, ng-zip2d-xl`, src: `images/117.jpg` },
    { prompt: `(The colonial city of the future, in the mist-filled Grand Canyon, on an unknown Earth-like planet, 2 moon on sky, Spaceship flight connects colonies:1.3), (Richard Meier:1.2), (Mario Botta:1.3), (avant-garde, future, reality, science fiction, photorealistic), (modern architecture:1.2),  (Large Files, Ultra Realistic, 8K, 16k, FHD, HD, VFX, Perfect, Photography, composition, Architecture Sales Photography, Architecture Competition, Ultra High Resolution, Cinematography, High Resolution Image:1.1), (dramatic lighting, direct sunlight, ray tracing, clear shadow:1.2),  (real landscape:1.1), (blurred background:1.0), (urban background, more_details) , ac_neg1, great lighting, clear, frames, cliffbuilding`, negprompt: `cartoon, painting, illustration, (worst quality, low quality, normal quality:1.8), (grayscale, teen:1.4)`, src: `images/118.jpg` },
    { prompt: `(futuristic:1.5) a huge military factory made of steel, glass, fog, sun, in the clouds, , futuristic military planes, moody tones, old book style ink cover illustration, on parchment,  (real landscape:1.1), (blurred background:1.0), [buildings|BREAK|trees|BREAK|Crowd|buildings|BREAK|trees|BREAK|Crowd|buildings|BREAK|trees|BREAK|Crowd:0.7], (background, more_details:0.3)  great lighting, clear, futureskyline`, negprompt: `(worst quality, greyscale), ac_neg2, zip2d_neg,  ziprealism_neg,  watermark, username, signature, text, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, jpeg artifacts, bad feet, extra fingers, mutated hands, poorly drawn hands, bad proportions, extra limbs, disfigured, bad anatomy, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, mutated hands, fused fingers, too many fingers, long neck`, src: `images/119.jpg` },
    { prompt: `cyberpunk, concept art, crowded street, background is night city, neon-lit, at Twilight, Depth of field 270mm, Technicolor, synthwave, neon hue, shadowrun`, negprompt: `character sheet, moody, monochromatic, washed out, natural, rustic, primitive, organic, simplistic, photograph, realism, photorealism, modern, ordinary, mundane, BREAK easynegative, low contrast, monochrome`, src: `images/120.jpg` },
    { prompt: `cyberpunk, concept art, crowded street, background is night city, neon-lit, at Twilight, Depth of field 270mm, Technicolor, synthwave, neon hue, shadowrun`, negprompt: `character sheet, moody, monochromatic, washed out, natural, rustic, primitive, organic, simplistic, photograph, realism, photorealism, modern, ordinary, mundane, BREAK easynegative, low contrast, monochrome`, src: `images/other-19.jpg` },
    { prompt: `a nighttime urban race with neon lights illuminating the track and surrounding buildings. The cars could be shown swerving around corners, with glowing brake lights and exhaust flames adding to the intensity of the scene`, negprompt: ``, src: `images/121.jpg` },
    { prompt: `colombia, train on the tracks, surrounded by flowers, on top green grass, river, in the style of cute cartoonish designs, dreamlike visuals, soft sculptures, webcam, bright colors, bold shapes, coastal landscapes, capturing moments, soft color, matte color, Ghibli style`, negprompt: `blurry, worst quality, text, logo`, src: `images/122.jpg` },
    { prompt: `colombia, train on the tracks, surrounded by flowers, on top green grass, river, in the style of cute cartoonish designs, dreamlike visuals, soft sculptures, webcam, bright colors, bold shapes, coastal landscapes, capturing moments, soft color, matte color, Ghibli style`, negprompt: `blurry, worst quality, text, logo`, src: `images/other-18.jpg` },
    { prompt: `gfsqm, tree, scenery, mountain,night, reflection, sky, outdoors, night sky, full moon, mountain, moonlight`, negprompt: `nsfw, ng_deepnegative_v1_75t,badhandv4, (worst quality:2), (low quality:2), (normal quality:2), lowres,watermark, monochrome,nsfw`, src: `images/123.jpg` },
    { prompt: `gfsqm, tree, scenery, mountain,night, reflection, sky, outdoors, night sky, full moon, mountain, moonlight`, negprompt: `nsfw, ng_deepnegative_v1_75t,badhandv4, (worst quality:2), (low quality:2), (normal quality:2), lowres,watermark, monochrome,nsfw`, src: `images/124.jpg` },
    { prompt: `a photo a fleet of alien ships coming through a rift in the sky over New York city, cinematic composition, cinematic lighting`, negprompt: `illustration, drawing, painting, sketch, 3D, render, manga, child, childlike`, src: `images/125.jpg` },
    { prompt: `people standing, outdoors, ,(masterpiece),(detailed),(intricate details),(realistic, photo-realistic:1.37),illustration,an extremely delicate and beautiful,8k wallpaper,absurdres,incredibly absurdres,ultra-detailed,highres,extremely detailed,`, negprompt: `EasyNegativeV2,  bad-hands-5, By bad artist -neg, ((navel piercing,nail polish,mole)),(worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale))`, src: `images/126.jpg` },
    { prompt: `people standing, outdoors, ,(masterpiece),(detailed),(intricate details),(realistic, photo-realistic:1.37),illustration,an extremely delicate and beautiful,8k wallpaper,absurdres,incredibly absurdres,ultra-detailed,highres,extremely detailed,`, negprompt: `EasyNegativeV2,  bad-hands-5, By bad artist -neg, ((navel piercing,nail polish,mole)),(worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale))`, src: `images/127.jpg` },
    { prompt: `people standing, outdoors, ,(masterpiece),(detailed),(intricate details),(realistic, photo-realistic:1.37),illustration,an extremely delicate and beautiful,8k wallpaper,absurdres,incredibly absurdres,ultra-detailed,highres,extremely detailed,`, negprompt: `EasyNegativeV2,  bad-hands-5, By bad artist -neg, ((navel piercing,nail polish,mole)),(worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale))`, src: `images/128.jpg` },
    { prompt: `people standing, outdoors, ,(masterpiece),(detailed),(intricate details),(realistic, photo-realistic:1.37),illustration,an extremely delicate and beautiful,8k wallpaper,absurdres,incredibly absurdres,ultra-detailed,highres,extremely detailed,`, negprompt: `EasyNegativeV2,  bad-hands-5, By bad artist -neg, ((navel piercing,nail polish,mole)),(worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale))`, src: `images/129.jpg` },
    { prompt: `people standing, outdoors, ,(masterpiece),(detailed),(intricate details),(realistic, photo-realistic:1.37),illustration,an extremely delicate and beautiful,8k wallpaper,absurdres,incredibly absurdres,ultra-detailed,highres,extremely detailed,`, negprompt: `EasyNegativeV2,  bad-hands-5, By bad artist -neg, ((navel piercing,nail polish,mole)),(worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale))`, src: `images/130.jpg` },

    { prompt: `people standing, outdoors, ,(masterpiece),(detailed),(intricate details),(realistic, photo-realistic:1.37),illustration,an extremely delicate and beautiful,8k wallpaper,absurdres,incredibly absurdres,ultra-detailed,highres,extremely detailed,`, negprompt: `EasyNegativeV2,  bad-hands-5, By bad artist -neg, ((navel piercing,nail polish,mole)),(worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale))`, src: `images/131.jpg` },
    { prompt: `people standing, outdoors, ,(masterpiece),(detailed),(intricate details),(realistic, photo-realistic:1.37),illustration,an extremely delicate and beautiful,8k wallpaper,absurdres,incredibly absurdres,ultra-detailed,highres,extremely detailed,`, negprompt: `EasyNegativeV2,  bad-hands-5, By bad artist -neg, ((navel piercing,nail polish,mole)),(worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale))`, src: `images/132.jpg` },
    { prompt: `people standing, outdoors, ,(masterpiece),(detailed),(intricate details),(realistic, photo-realistic:1.37),illustration,an extremely delicate and beautiful,8k wallpaper,absurdres,incredibly absurdres,ultra-detailed,highres,extremely detailed,`, negprompt: `EasyNegativeV2,  bad-hands-5, By bad artist -neg, ((navel piercing,nail polish,mole)),(worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale))`, src: `images/133.jpg` },
    { prompt: `people standing, outdoors, ,(masterpiece),(detailed),(intricate details),(realistic, photo-realistic:1.37),illustration,an extremely delicate and beautiful,8k wallpaper,absurdres,incredibly absurdres,ultra-detailed,highres,extremely detailed,`, negprompt: `EasyNegativeV2,  bad-hands-5, By bad artist -neg, ((navel piercing,nail polish,mole)),(worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale))`, src: `images/134.jpg` },
];

/* START */
changeColumnNumbers();
/* START */

window.addEventListener("resize", changeColumnNumbers);

function checkColumnsNumber() {
    let number = 0;
    flexColumns.forEach((item) => {
        if (getComputedStyle(item).display == "flex") {
            number++;
        }
    });
    return number;
}

function changeColumnNumbers() {
    const columnNumbers = checkColumnsNumber();
    flexColumns.forEach((item) => {
        item.textContent = "";
    });

    let columnIndex = 0;
    for (let i = 0; i < imageTable.length; i++) {
        const newImg = document.createElement("img");
        newImg.src = imageTable[i].src;
        newImg.addEventListener("click", setImageDataToLocalStorage);
        newImg.addEventListener("click", copyMessageAnimation);
        newImg.classList.add("pointer");
        flexColumns[columnIndex].appendChild(newImg);

        columnIndex++;
        if (columnIndex % columnNumbers == 0) {
            columnIndex = 0;
        }
    }
}

function setImageDataToLocalStorage() {
    let indexOfSearchedItem;
    imageTable.forEach((item, index) => {
        if (item.src == this.getAttribute("src")) {
            indexOfSearchedItem = index;
        }
    });
    sessionStorage.setItem("copiedData", JSON.stringify(imageTable[indexOfSearchedItem]));
}

function copyMessageAnimation() {
    const copyMessage = document.querySelector(".copyMessage");
    copyMessage.classList.remove("copyMessageAnimationTrigger");
    setTimeout(() => {
        copyMessage.classList.add("copyMessageAnimationTrigger");
    }, 100);
}
